name: PR Title Linter
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Validate title
        uses: warp-ds/pr-linter@v1
