name: PR Title Checker

on:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]
    branches: 
      - '*'
      - '!main'

jobs:
  lint:
    name: Validate PR Title
    runs-on: ubuntu-latest
    if: ${{github.event.pull_request.base.ref == 'next'}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: current
      - name : Print Title of PR
        uses: actions/github-script@v6
        id: pr-title
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: json
          script: |
            const { data: pr } = await github.rest.issues.get({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            return pr.title;
      - name : Test Title of PR
        uses: actions/github-script@v6
        id: pr-title-check
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: json
          script: |
            const prefixes = ['fix:', 'feat:', 'chore:', 'docs:', 'style:', 'refactor:', 'perf:', 'test'];
            const prTitle = ${{steps.pr-title.outputs.result}};
            const hasPrefix = prefixes.find(prefix => { return prTitle.includes(prefix) });
            return !hasPrefix;
      - name: Update PR Comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: json
          script: |
            // Retrieve existing bot comments for the PR
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            const botComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes('Incorrect Pull Request Title Format')
            });

            if (${{steps.pr-title-check.outputs.result}}) {
              const output = `**Incorrect Pull Request Title Format**
               The title of this pull request does not appear to match the commit message format.
                \`\`\`
                Examples from Commitizen
                \`\`\`
                 ![](https://github.com/commitizen/cz-cli/raw/master/meta/screenshots/add-commit.png)
                `;
              // If we have a comment, update it, otherwise create a new one
              if (botComment) {
                github.rest.issues.updateComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: botComment.id,
                  body: output
                });
              } else {
                github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: output
                });
              }
              return;
            }
            if (botComment) {
              github.rest.issues.deleteComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id
              });
              return;
            }
      - name: Check PR Title Status
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: json
          script: |
            const hasError = ${{steps.pr-title-check.outputs.result}};
            if (hasError) {
              core.setFailed('PR Title Checker job has failed!');
            }
