name: Release
on:
  push:
    branches:
      - master
      - next
jobs:
  test-and-build:
    uses: ./test.js.yml
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
